In [2]:
import pandas as pd
import numpy as np

In [3]:
population = pd.read_csv("API_SP.POP.TOTL_DS2_en_csv_v2_4751604.csv", skiprows=4)
population = population.drop("Unnamed: 66", axis=1)
population

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54208.0,55434.0,56234.0,56699.0,57029.0,57357.0,...,102565.0,103165.0,103776.0,104339.0,104865.0,105361.0,105846.0,106310.0,106766.0,107195.0
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130836765.0,134159786.0,137614644.0,141202036.0,144920186.0,148769974.0,...,547482863.0,562601578.0,578075373.0,593871847.0,609978946.0,626392880.0,643090131.0,660046272.0,677243299.0,694665117.0
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8996967.0,9169406.0,9351442.0,9543200.0,9744772.0,9956318.0,...,31161378.0,32269592.0,33370804.0,34413603.0,35383028.0,36296111.0,37171922.0,38041757.0,38928341.0,39835428.0
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,96396419.0,98407221.0,100506960.0,102691339.0,104953470.0,107289875.0,...,370243017.0,380437896.0,390882979.0,401586651.0,412551299.0,423769930.0,435229381.0,446911598.0,458803476.0,470898870.0
4,Angola,AGO,"Population, total",SP.POP.TOTL,5454938.0,5531451.0,5608499.0,5679409.0,5734995.0,5770573.0,...,25107925.0,26015786.0,26941773.0,27884380.0,28842482.0,29816769.0,30809787.0,31825299.0,32866268.0,33933611.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Population, total",SP.POP.TOTL,947000.0,966000.0,994000.0,1022000.0,1050000.0,1078000.0,...,1807106.0,1818117.0,1812771.0,1788196.0,1777557.0,1791003.0,1797085.0,1788878.0,1790133.0,1806279.0
262,"Yemen, Rep.",YEM,"Population, total",SP.POP.TOTL,5315351.0,5393034.0,5473671.0,5556767.0,5641598.0,5727745.0,...,24473176.0,25147112.0,25823488.0,26497881.0,27168210.0,27834811.0,28498683.0,29161922.0,29825968.0,30490639.0
263,South Africa,ZAF,"Population, total",SP.POP.TOTL,17099836.0,17524533.0,17965733.0,18423157.0,18896303.0,19384838.0,...,52832659.0,53687125.0,54544184.0,55386369.0,56207649.0,57009751.0,57792520.0,58558267.0,59308690.0,60041996.0
264,Zambia,ZMB,"Population, total",SP.POP.TOTL,3070780.0,3164330.0,3260645.0,3360099.0,3463211.0,3570466.0,...,14465148.0,14926551.0,15399793.0,15879370.0,16363449.0,16853608.0,17351714.0,17861034.0,18383956.0,18920657.0
265,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,3776679.0,3905038.0,4039209.0,4178726.0,4322854.0,4471178.0,...,13115149.0,13350378.0,13586710.0,13814642.0,14030338.0,14236599.0,14438812.0,14645473.0,14862927.0,15092171.0

In [4]:
co2_emissions = pd.read_csv("co2-fossil-by-nation_zip/data/fossil-fuel-co2-emissions-by-nation_csv.csv", skiprows=0)
co2_emissions

,Year,Country,Total,Solid Fuel,Liquid Fuel,Gas Fuel,Cement,Gas Flaring,Per Capita,Bunker fuels (Not in Total)
0,1751,UNITED KINGDOM,2552,2552,0,0,0,0,0.00,0
1,1752,UNITED KINGDOM,2553,2553,0,0,0,0,0.00,0
2,1753,UNITED KINGDOM,2553,2553,0,0,0,0,0.00,0
3,1754,UNITED KINGDOM,2554,2554,0,0,0,0,0.00,0
4,1755,UNITED KINGDOM,2555,2555,0,0,0,0,0.00,0
...,...,...,...,...,...,...,...,...,...,...
17227,2014,VIET NAM,45517,19246,12694,5349,8229,0,0.49,761
17228,2014,WALLIS AND FUTUNA ISLANDS,6,0,6,0,0,0,0.44,1
17229,2014,YEMEN,6190,137,5090,581,381,0,0.24,153
17230,2014,ZAMBIA,1228,132,797,0,299,0,0.08,33
17231,2014,ZIMBABWE,3278,2097,1005,0,177,0,0.22,9

In [5]:
gdp = pd.read_csv("API_NY.GDP.MKTP.CD_DS2_en_csv_v2_4751562/API_NY.GDP.MKTP.CD_DS2_en_csv_v2_4751562.csv", skiprows=4)
gdp = gdp.drop("Unnamed: 66", axis=1)
gdp

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.615084e+09,2.727933e+09,2.791061e+09,2.963128e+09,2.983799e+09,3.092179e+09,3.202235e+09,3.310056e+09,2.496648e+09,NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,2.129059e+10,2.180847e+10,2.370702e+10,2.821004e+10,2.611879e+10,2.968217e+10,...,9.730435e+11,9.839370e+11,1.003679e+12,9.242525e+11,8.823551e+11,1.020647e+12,9.910223e+11,9.975340e+11,9.216459e+11,1.082096e+12
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,...,1.990732e+10,2.014640e+10,2.049713e+10,1.913421e+10,1.811656e+10,1.875347e+10,1.805323e+10,1.879945e+10,2.011614e+10,NaN
3,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,1.040414e+10,1.112789e+10,1.194319e+10,1.267633e+10,1.383837e+10,1.486223e+10,...,7.275704e+11,8.207927e+11,8.649905e+11,7.607345e+11,6.905464e+11,6.837487e+11,7.416899e+11,7.945430e+11,7.844457e+11,8.358084e+11
4,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.249982e+11,1.334016e+11,1.372444e+11,8.721929e+10,4.984049e+10,6.897276e+10,7.779294e+10,6.930910e+10,5.361907e+10,7.254699e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,6.163785e+09,6.735731e+09,7.074658e+09,6.295820e+09,6.682833e+09,7.180813e+09,7.878509e+09,7.899879e+09,7.716925e+09,9.007159e+09
262,"Yemen, Rep.",YEM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.540134e+10,4.041524e+10,4.322859e+10,4.244450e+10,3.131783e+10,2.684223e+10,2.160616e+10,2.188761e+10,1.884051e+10,2.106169e+10
263,South Africa,ZAF,GDP (current US$),NY.GDP.MKTP.CD,8.748597e+09,9.225996e+09,9.813996e+09,1.085420e+10,1.195600e+10,1.306899e+10,...,4.344005e+11,4.008860e+11,3.811989e+11,3.467098e+11,3.235855e+11,3.814488e+11,4.048421e+11,3.879346e+11,3.354421e+11,4.199464e+11
264,Zambia,ZMB,GDP (current US$),NY.GDP.MKTP.CD,7.130000e+08,6.962857e+08,6.931429e+08,7.187143e+08,8.394286e+08,1.082857e+09,...,2.550306e+10,2.803724e+10,2.714102e+10,2.125122e+10,2.095841e+10,2.587360e+10,2.631159e+10,2.330867e+10,1.811063e+10,2.120306e+10
265,Zimbabwe,ZWE,GDP (current US$),NY.GDP.MKTP.CD,1.052990e+09,1.096647e+09,1.117602e+09,1.159512e+09,1.217138e+09,1.311436e+09,...,1.711485e+10,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,1.758489e+10,1.811554e+10,1.928429e+10,1.805117e+10,2.621773e+10

In [7]:
#czy nazwy krajów są takie same w population i gdp
if population["Country Name"].tolist() == gdp["Country Name"].tolist():
    print(1)
else:
    print(0)
    #i usuń złe kraje

1

In [48]:
#wstępna tabelka dla jednego roku
#ustalony rok
def find_5_countries_gdp(countries_names_list, population_list, gpd_list, year): #tu już mamy w np.array
    if np.isnan(population_list).any():
        population_list = np.nan_to_num(population_list, nan=-1)
        #wypisać które państwo
        print("WARNING: There are countries with no data regarding population in year", end="")
        print(year)
    if np.isnan(gpd_list).any():
        #wypisać gdzie nie ma gpd
        gpd_list = np.nan_to_num(gpd_list, nan=0)
        print("WARNING: There are countries with no data regarding gpd in year")
        print(year)
    
    #co gdy mniej niż 5 krajów
    gpd_on_person = gpd_list/population_list
    #print(gpd_on_person)
    indexes = np.argsort(gpd_on_person)[::-1][:5]
    kraj = countries_names_list[indexes]
    gpdDpopul = gpd_on_person[indexes]
    #print(gpd_on_person[indexes])
    gpd_sum = gpd_list[indexes]
    ##########problem z population_list, chyba ma 0
    tabelka = np.array([kraj, gpdDpopul, gpd_sum])
    tabelka = np.transpose(tabelka)
    df = pd.DataFrame(tabelka, columns = ['kraj', 'gpdDpopul', 'gpd_sum'])
    return df
        
#rok	nr	kraj	gpd/popul
#2000	1	Poland	2137zł	308932683282zł
#2000	2	England	6789zł	9732632629692zł

In [49]:
y = "1992"
cnl = population["Country Name"].to_numpy()
pl = population[y].to_numpy()
gdpl = gdp[y].to_numpy()

tab = find_5_countries_gdp(cnl, pl, gdpl, y)
tab

WARNING: There are countries with no data regarding population in year1992
WARNING: There are countries with no data regarding gpd in year
1992

            kraj     gpdDpopul              gpd_sum
0         Monaco  91670.604007     2737192565.05576
1  Liechtenstein  55197.547011       1631197909.259
2    Switzerland  40747.925462  280156819798.036987
3     Luxembourg  39570.861567     15518702634.8808
4         Sweden  32800.982687  284321115594.629028

In [58]:
for i in range(1960,2022):
    y = str(i)
    cnl = population["Country Name"].to_numpy()
    pl = population[y].to_numpy()
    gdpl = gdp[y].to_numpy()

    tab = find_5_countries_gdp(cnl, pl, gdpl, y)
    print(tab)

WARNING: There are countries with no data regarding population in year1960
WARNING: There are countries with no data regarding gpd in year
1960
            kraj    gpdDpopul              gpd_sum
0  United States  3007.123445       543300000000.0
1  North America  2939.448335  583846188346.723999
2    New Zealand  2312.949992     5485854791.97096
3         Canada  2259.294285   40461721692.646797
4     Luxembourg  2242.015817     703925705.942958
WARNING: There are countries with no data regarding population in year1961
WARNING: There are countries with no data regarding gpd in year
1961
            kraj    gpdDpopul              gpd_sum
0  United States  3066.562869       563300000000.0
1  North America  2991.592897  604324202050.644043
2    New Zealand  2343.292213     5670064168.21773
3         Sweden  2288.921701   17212686614.572601
4         Canada  2240.433039     40934952063.9468
WARNING: There are countries with no data regarding population in year1962
WARNING: There are countries with no data regarding gpd in year
1962
            kraj    gpdDpopul              gpd_sum
0  United States  3243.843078       605100000000.0
1  North America  3155.097538  647421597617.883057
2         Sweden  2468.694589     18667251380.0746
3    New Zealand  2448.628633     6077496267.76294
4     Luxembourg  2311.798849     741509480.796284
WARNING: There are countries with no data regarding population in year1963
WARNING: There are countries with no data regarding gpd in year
1963
            kraj    gpdDpopul              gpd_sum
0  United States  3374.515171       638600000000.0
1  North America  3283.141453  683726355213.515991
2         Sweden  2657.022505   20204870629.744099
3    New Zealand  2622.220271     6638937283.13963
4     Luxembourg  2441.038555     791140595.772755
WARNING: There are countries with no data regarding population in year1964
WARNING: There are countries with no data regarding gpd in year
1964
            kraj    gpdDpopul              gpd_sum
0  United States  3573.941185       685800000000.0
1  North America  3480.426945  735285089547.337036
2         Sweden  2941.048899   22532416750.012501
3    New Zealand  2813.546976     7274144350.81809
4     Luxembourg  2755.633117     903158753.943622
WARNING: There are countries with no data regarding population in year1965
WARNING: There are countries with no data regarding gpd in year
1965
            kraj    gpdDpopul              gpd_sum
0         Kuwait  4443.452338      2097451694.2033
1  United States   3827.52711       743700000000.0
2  North America  3729.969704  798329518629.680054
3         Sweden   3206.09917   24795499685.775002
4     Luxembourg  2780.092719     921600736.304026
WARNING: There are countries with no data regarding population in year1966
WARNING: There are countries with no data regarding gpd in year
1966
            kraj    gpdDpopul              gpd_sum
0         Kuwait  4571.155742     2391486978.43741
1  United States  4146.316646       815000000000.0
2  North America  4044.247215  876222557410.437988
3         Sweden  3454.429789   26971486546.284801
4        Iceland  3215.694178     628893310.399926
WARNING: There are countries with no data regarding population in year1967
WARNING: There are countries with no data regarding gpd in year
1967
            kraj    gpdDpopul              gpd_sum
0  United States  4336.426587       861700000000.0
1  North America  4231.867351  927523758485.753052
2         Kuwait  4230.847778     2441893027.16326
3         Sweden  3720.926845   29275995674.688801
4         Canada  3217.159294   65668655501.125397
WARNING: There are countries with no data regarding population in year1968
WARNING: There are countries with no data regarding gpd in year
1968
            kraj    gpdDpopul               gpd_sum
0  United States   4695.92339        942500000000.0
1  North America   4579.98226  1014479810519.900024
2         Kuwait  4207.731536      2663119574.34892
3         Sweden  3926.409001    31066819929.285301
4         Canada  3462.678872    71829810519.895493
WARNING: There are countries with no data regarding population in year1969
WARNING: There are countries with no data regarding gpd in year
1969
            kraj    gpdDpopul               gpd_sum
0  United States  5032.144743       1019900000000.0
1  North America  4912.487595  1099213311661.689941
2         Sweden  4234.161348      33738102482.1558
3         Kuwait  4019.803916      2769532343.88127
4         Canada  3763.953379    79148411661.690201
WARNING: There are countries with no data regarding population in year1970
WARNING: There are countries with no data regarding gpd in year
1970
            kraj     gpdDpopul               gpd_sum
0         Monaco  12478.131223      293073868.038497
1  United States   5234.296666       1073303000000.0
2  North America   5129.091844  1161385395320.129883
3         Sweden   4736.217154    38092452060.620102
4     Luxembourg   4298.033897      1457768455.02219
WARNING: There are countries with no data regarding population in year1971
WARNING: There are countries with no data regarding gpd in year
1971
            kraj     gpdDpopul               gpd_sum
0         Monaco  13812.718181      327651487.974965
1  United States     5609.3826       1164850000000.0
2  North America   5504.815818  1264333061774.610107
3         Sweden   5132.711607    41566412922.608704
4         Kuwait   4858.728915      3880370401.57259
WARNING: There are countries with no data regarding population in year1972
WARNING: There are countries with no data regarding gpd in year
1972
            kraj     gpdDpopul               gpd_sum
0         Monaco  16735.013233      402460333.247989
1  United States    6094.01799       1279110000000.0
2         Sweden   6027.128499    48954145808.835899
3  North America   5997.485632  1392428220486.919922
4  Liechtenstein   5637.919093      124941925.010473
WARNING: There are countries with no data regarding population in year1973
WARNING: There are countries with no data regarding gpd in year
1973
            kraj     gpdDpopul             gpd_sum
0         Monaco  21417.582945    523552815.099552
1     Luxembourg   7447.213018    2609875802.11136
2  Liechtenstein   7355.080307    165930611.729019
3         Sweden   7301.215426  59404966684.221397
4  United States   6726.358956     1425376000000.0
WARNING: There are countries with no data regarding population in year1974
WARNING: There are countries with no data regarding gpd in year
1974
            kraj     gpdDpopul           gpd_sum
0         Monaco   22712.94336  563939670.684242
1          Qatar  15631.693143  2401403227.44085
2         Kuwait  13521.667334  13004774556.6166
3     Luxembourg   8966.728959  3183637116.81856
4  Liechtenstein   8439.578876  193983720.461869
WARNING: There are countries with no data regarding population in year1975
WARNING: There are countries with no data regarding gpd in year
1975
                   kraj     gpdDpopul             gpd_sum
0                Monaco  28247.549667     711922994.25844
1  United Arab Emirates  26848.088176  14720672506.500401
2                 Qatar  15292.574177    2512784033.37828
3                Kuwait  11768.468302  12024138275.862101
4         Liechtenstein   10513.20529    246387479.177159
WARNING: There are countries with no data regarding population in year1976
WARNING: There are countries with no data regarding gpd in year
1976
                   kraj     gpdDpopul             gpd_sum
0  United Arab Emirates  30117.948933  19213022691.052601
1                Monaco  28810.873013     735339911.91765
2                 Qatar  18906.153332    3284301332.18953
3                Kuwait  12093.268365  13131668946.648399
4         Liechtenstein  11385.696696    272493879.020643
WARNING: There are countries with no data regarding population in year1977
WARNING: There are countries with no data regarding gpd in year
1977
                   kraj     gpdDpopul             gpd_sum
0  United Arab Emirates  33823.181661  24871775164.604301
1                Monaco  31430.433822    811250927.388123
2                 Qatar  19842.036056    3617580171.76055
3         Liechtenstein  12412.427969    303496276.263782
4                Kuwait  12253.866542    14135729588.2763
WARNING: There are countries with no data regarding population in year1978
WARNING: There are countries with no data regarding gpd in year
1978
                   kraj     gpdDpopul           gpd_sum
0                Monaco   38349.39576  1000535735.37664
1  United Arab Emirates  28457.078034  23775831783.4263
2                 Qatar  21109.996055  4052000412.70087
3         Liechtenstein  17499.125951  436918176.733781
4            Luxembourg  13034.388208  4718539771.99949
WARNING: There are countries with no data regarding population in year1979
WARNING: There are countries with no data regarding gpd in year
1979
                   kraj     gpdDpopul             gpd_sum
0                Monaco  45845.109825    1209898293.39444
1  United Arab Emirates  33512.633424  31225463217.758202
2                 Qatar  27455.014905    5633000318.02401
3         Liechtenstein  19761.248478    503180669.994587
4                Kuwait  19093.016493     24746019536.903
WARNING: There are countries with no data regarding population in year1980
WARNING: There are countries with no data regarding gpd in year
1980
                   kraj     gpdDpopul             gpd_sum
0                Monaco   51515.06413    1378130995.60185
1  United Arab Emirates  42764.540556  43598748449.047897
2                 Qatar  35010.395279    7829094613.07082
3     Brunei Darussalam  25422.039189    4928824957.96749
4                Kuwait  20924.212014  28638550499.445099
WARNING: There are countries with no data regarding population in year1981
WARNING: There are countries with no data regarding gpd in year
1981
                   kraj     gpdDpopul             gpd_sum
0  United Arab Emirates   44987.53799  49333424135.113098
1                Monaco  44369.561353    1205166025.47602
2                 Qatar  34926.703996   8661263763.736259
3     Brunei Darussalam  21828.122451    4366213849.57637
4         Liechtenstein  19507.365533    511658690.561043
WARNING: There are countries with no data regarding population in year1982
WARNING: There are countries with no data regarding gpd in year
1982
                   kraj     gpdDpopul             gpd_sum
0                Monaco  41371.876808    1143229071.83219
1  United Arab Emirates  40025.822624  46622718605.284698
2                 Qatar  27402.267491    7596703214.28571
3     Brunei Darussalam  20693.824911     4264252336.4486
4         Liechtenstein  19677.018486    522090331.478107
WARNING: There are countries with no data regarding population in year1983
WARNING: There are countries with no data regarding gpd in year
1983
                   kraj     gpdDpopul             gpd_sum
0                Monaco   38893.30323    1092551781.03673
1  United Arab Emirates  34843.159626  42803323345.137604
2                 Qatar   20910.45334    6467582307.69231
3         Liechtenstein  19560.810372    524034109.856605
4     Brunei Darussalam  18129.243904    3844723142.45149
WARNING: There are countries with no data regarding population in year1984
WARNING: There are countries with no data regarding gpd in year
1984
                   kraj     gpdDpopul           gpd_sum
0                Monaco  36382.973457  1037314956.23209
1  United Arab Emirates  32309.832713   41807954235.903
2                 Qatar  19645.314659  6704395824.17582
3         Liechtenstein  18596.172688  502617355.407073
4               Bermuda  17469.825568       985699968.0
WARNING: There are countries with no data regarding population in year1985
WARNING: There are countries with no data regarding gpd in year
1985
                   kraj     gpdDpopul             gpd_sum
0                Monaco  37552.055642    1082851076.49699
1  United Arab Emirates  29720.897718  40603650231.544502
2         Liechtenstein  19390.126642    529078995.563876
3               Bermuda   18269.53552        1039500032.0
4         United States  18236.827727     4338979000000.0
WARNING: There are countries with no data regarding population in year1986
WARNING: There are countries with no data regarding gpd in year
1986
                   kraj     gpdDpopul              gpd_sum
0                Monaco  52158.677735     1515209588.20845
1         Liechtenstein  28287.063284     779365167.602424
2           Switzerland  24480.422564  159223703930.179993
3  United Arab Emirates  23467.879318     33943612094.7971
4               Bermuda  20450.664529         1173500032.0
WARNING: There are countries with no data regarding population in year1987
WARNING: There are countries with no data regarding gpd in year
1987
                   kraj     gpdDpopul              gpd_sum
0                Monaco  63077.774568     1839095595.29143
1         Liechtenstein  37824.442164     1052843347.63948
2           Switzerland  30466.109022  199403912956.009003
3  United Arab Emirates  23726.307049   36384908744.211403
4                Norway  22505.897712   94230055658.627106
WARNING: There are countries with no data regarding population in year1988
WARNING: There are countries with no data regarding gpd in year
1988
            kraj     gpdDpopul               gpd_sum
0         Monaco  68441.251612       2000674667.1353
1  Liechtenstein  41292.257722      1161757671.01756
2    Switzerland  32717.920448   215721878630.493011
3     Luxembourg  25219.354278      9418167855.18376
4          Japan  25059.007433  3071683013178.910156
WARNING: There are countries with no data regarding population in year1989
WARNING: There are countries with no data regarding gpd in year
1989
            kraj     gpdDpopul              gpd_sum
0         Monaco  68583.604055     2010116851.24167
1  Liechtenstein  39368.727088     1120000916.92646
2    Switzerland  31334.979079  208280848462.619995
3     Luxembourg  26618.069577      10037674037.674
4         Sweden  25662.220589  217948315624.563995
WARNING: There are countries with no data regarding population in year1990
WARNING: There are countries with no data regarding gpd in year
1990
            kraj     gpdDpopul              gpd_sum
0         Monaco  84303.878435     2481316053.96507
1  Liechtenstein  49373.610266     1421466239.56234
2    Switzerland  39607.819086  265987061618.197998
3     Luxembourg  33465.478208   12778792853.693899
4         Sweden  30593.672445   261846194498.88501
WARNING: There are countries with no data regarding population in year1991
WARNING: There are countries with no data regarding gpd in year
1991
            kraj     gpdDpopul              gpd_sum
0         Monaco  83721.991422     2480598883.85071
1  Liechtenstein  50886.375311      1484152022.3152
2    Switzerland  39577.748749  269127820781.032013
3     Luxembourg  35747.337799   13834219728.292999
4         Sweden  31822.803848  274229034311.699005
WARNING: There are countries with no data regarding population in year1992
WARNING: There are countries with no data regarding gpd in year
1992
            kraj     gpdDpopul              gpd_sum
0         Monaco  91670.604007     2737192565.05576
1  Liechtenstein  55197.547011       1631197909.259
2    Switzerland  40747.925462  280156819798.036987
3     Luxembourg  39570.861567     15518702634.8808
4         Sweden  32800.982687  284321115594.629028
WARNING: There are countries with no data regarding population in year1993
WARNING: There are countries with no data regarding gpd in year
1993
            kraj     gpdDpopul               gpd_sum
0         Monaco  85397.326558      2574302409.08038
1  Liechtenstein  55794.327334      1673104493.77369
2     Luxembourg  40066.724252      15925521222.0149
3    Switzerland  39270.114135   272466458446.128998
4          Japan  35681.963942  4454143876947.209961
WARNING: There are countries with no data regarding population in year1994
WARNING: There are countries with no data regarding gpd in year
1994
            kraj     gpdDpopul               gpd_sum
0         Monaco  89378.039785      2720310018.90359
1  Liechtenstein   64051.23221      1948118227.68151
2     Luxembourg  43933.235443      17701798890.7644
3    Switzerland  43128.014109   301628489434.817993
4          Japan  39933.515056  4998797547740.969727
WARNING: There are countries with no data regarding population in year1995
WARNING: There are countries with no data regarding gpd in year
1995
            kraj      gpdDpopul               gpd_sum
0         Monaco  101866.604083      3130462610.06703
1  Liechtenstein   78631.699111      2428461395.34884
2     Luxembourg   51032.349635      20853093869.7318
3    Switzerland   50155.974127   353132515010.570984
4          Japan   44197.619101  5545563663889.700195
WARNING: There are countries with no data regarding population in year1996
WARNING: There are countries with no data regarding gpd in year
1996
            kraj      gpdDpopul             gpd_sum
0         Monaco  101212.002563    3137673291.44762
1  Liechtenstein   79863.279085    2504033252.42718
2     Luxembourg   50444.359124  20895314657.980499
3    Switzerland   48144.579128  340471241909.38501
4        Bermuda    44826.78907        2695390000.0
WARNING: There are countries with no data regarding population in year1997
WARNING: There are countries with no data regarding gpd in year
1997
            kraj     gpdDpopul              gpd_sum
0         Monaco  90833.297463     2840175545.06631
1  Liechtenstein  72208.934674     2298410390.68421
2        Bermuda   48478.88325         2932827000.0
3     Luxembourg  46641.640875   19563836265.223301
4    Switzerland  41631.438859  295121356714.669983
WARNING: There are countries with no data regarding population in year1998
WARNING: There are countries with no data regarding gpd in year
1998
            kraj     gpdDpopul              gpd_sum
0         Monaco  92999.253451     2934498443.40672
1  Liechtenstein  76757.300219      2479721340.8746
2        Bermuda  51371.740807         3130748000.0
3     Luxembourg  47445.381081   20150053345.187801
4    Switzerland  42740.128183  303882354117.809021
WARNING: There are countries with no data regarding population in year1999
WARNING: There are countries with no data regarding gpd in year
1999
              kraj     gpdDpopul           gpd_sum
0           Monaco  91283.256586  2906093756.65885
1    Liechtenstein  81307.068367  2664026095.06058
2          Bermuda  54245.459737      3324433000.0
3       Luxembourg  50872.449268  21899317598.8414
4  Channel Islands   42446.97122  6263177944.41707
WARNING: There are countries with no data regarding population in year2000
WARNING: There are countries with no data regarding gpd in year
2000
              kraj     gpdDpopul           gpd_sum
0           Monaco  82365.492365   2647885848.5351
1    Liechtenstein  74853.938729  2483953102.79488
2          Bermuda  56284.168648      3480219000.0
3       Luxembourg  48659.598875  21230182989.3036
4  Channel Islands  43380.802983   6439403014.0037
WARNING: There are countries with no data regarding population in year2001
WARNING: There are countries with no data regarding gpd in year
2001
              kraj     gpdDpopul           gpd_sum
0           Monaco  83724.465912  2718868306.01093
1    Liechtenstein  74287.413374  2491822706.80256
2          Bermuda  58883.959427      3680483000.0
3       Luxembourg  48440.142015  21387533703.2327
4  Channel Islands  41807.079018  6233310060.38969
WARNING: There are countries with no data regarding population in year2002
WARNING: There are countries with no data regarding gpd in year
2002
              kraj     gpdDpopul             gpd_sum
0           Monaco  90506.859506    2968987019.23077
1    Liechtenstein  79345.752473    2688630822.53304
2          Bermuda  62583.100203        3937228000.0
3       Luxembourg  53005.733921  23649833332.165501